---

- name: Find any rsyslog files where all logs are being forwarded to a loghost
  shell: >
    /usr/bin/grep -l -s -E '^\*\.\*\s+action\(type="omfwd"' {{ rsyslog_conf_path }} {{ rsyslogd_path }}/*.conf
  register: rsyslog_forward_out
  changed_when: false
  failed_when: rsyslog_forward_out.rc == "2"

#- debug: var=rsyslog_forward_out

- name: Forward journald logs to rsyslog IF rsyslog is sending logs to a log host
  vars:
    rsyslog_forwarding: "{{ rsyslog_forward_out.stdout | length > 0 }}"
    str: "{{ 'yes' if rsyslog_forwarding else 'no' }}"
  lineinfile:
    dest: "{{ journald_conf_path }}"
    regexp: "^#?ForwardToSyslog=.*$"
    line: "ForwardToSyslog={{ str }}"

- name: Ensure journald compresses large files
  vars:
    str: "{{ 'yes' if (journald_compress | default(true)) else 'no' }}"
  lineinfile:
    dest: "{{ journald_conf_path }}"
    regexp: "^#?Compress=.*$"
    line: "Compress={{ str }}"

- name: Ensure journald writes to peristent disk
  lineinfile:
    dest: "{{ journald_conf_path }}"
    regexp: "^#?Storage=.*$"
    line: "Storage=persistent"
