---
# tasks file for selinux
- name: include assert.yml
  include_tasks: assert.yml
  run_once: yes

#- debug: var=selinux_requirements

- name: install required packages
  package:
    name: "{{ selinux_requirements }}"
    state: present
    update_cache: yes

- name: manage selinux
  selinux:
    state: "{{ selinux_state }}"
    policy: "{{ selinux_policy }}"
  notify:
    - reboot
  when:
    - ansible_selinux.status is defined
    - ansible_connection != "docker"
