---
##
# This file provides all tasks related to package management.
# It starts by setting up some configuration on the package
# management system itself.
# It includes updating packages to latest version as well as
# installing and removing software.
##

- name: Update cache
  pacman:
    update_cache: yes
  changed_when: false

- name: Update all packages
  pacman:
    upgrade: yes
  when: pm_update_system
  notify: reboot

- name: Install packages
  apk:
    name: "{{ pm_install_packages }}"
    state: present

- name: Delete packages
  apk:
    name: "{{ pm_remove_packages }}"
    state: absent
    # Remove each target specified including all of their dependencies, provided that 
    # (A) they are not required by other packages; and 
    # (B) they were not explicitly installed by the user. 
    extra_args: "{{ '--recursive' if pm_autoremove else '' }}"
