---

- name: Validate numeric variables are correctly set
  assert:
    that:
      - vars[item] is defined
      - vars[item] | default(-1) | int(-1) > -1
    quiet: yes
  loop:
    - user_max_days
    - user_min_days
    - user_inactive_days
    - user_warn_age
    - user_umask
    - user_shell_timeout
  loop_control:
    label: "{{ item }}: {{ vars[item] | default('undefined') }}"

- name: Validate user_fix_existing_accounts value
  assert:
    that:
      - user_fix_existing_accounts is defined
      - user_fix_existing_accounts | type_debug == 'bool'
    quiet: yes

- name: Validate user_account_add information
  vars:
    pathre: '^(?:[\/])$|^(?:[\/][a-zA-Z0-9_.-]+)+[\/]?$'
  assert:
    that:
      - item.name is defined
      - item.name | length > 0
      - item.uid is undefined or (item.uid | int > 0)
      - item.shell is undefined or item.shell is regex(pathre)
      - item.password is undefined or item.password | length > 0
    quiet: yes
  loop: "{{ user_account_add }}"
  loop_control:
    label: "{{ item.name | default('undefined') }}"
  when: user_account_add is defined

- name: Validate user_group_add information
  assert:
    that:
      - item.name is defined
      - item.name | length > 0
      - item.gid is undefined or (item.gid | int > 0)
    quiet: yes
  loop: "{{ user_group_add }}"
  loop_control:
    label: "{{ item.name | default('undefined') }}"
  when: user_group_add is defined

- name: Validate users and groups to be removed
  assert:
    that:
      - item is defined
      - item | length > 0
    quiet: yes
  loop:
    - "{{ user_account_remove | default([]) }}"
    - "{{ user_group_remove | default([]) }}"
  when: user_account_remove is defined or user_group_remove is defined
