---

- name: Ensure correct permission on critical system files
  file:
    path: "{{ item.name }}"
    owner: "{{ item.owner }}"
    group: "{{ item.group }}"
    mode: "{{ item.mode }}"
  loop: "{{ user_critical_files_perms[ansible_os_family] }}"
  loop_control:
    label: "{{ item.name }}"
