---
# tasks file for user

# Check input variables
- name: Check input variables (include asserts.yml)
  include_tasks: asserts.yml

- name: Setting up login definitions (include set_login_defs.yml)
  include_tasks: set_login_defs.yml

- name: Ensure critical user/group management file have correct permissions (include file_permissions.yml)
  include_tasks: file_permissions.yml

- name: Ensure root password is set and single user mode is configured correctly (include root_singleuser.yml)
  include_tasks: root_singleuser.yml

- name: Manage users and groups (include user_group_management.yml)
  include_tasks: user_group_management.yml

- name: Search/Fix/Report users with invalid settings
  include_tasks: fix_users.yml


