---

# Loop through provided list and ensure group is in the system, with correct attributes
- name: Ensure specified groups exist with correct attributes
  group:
    name: "{{ item.name }}"
    gid: "{{ item.uid | default(omit) }}"
    state: present
  loop: "{{ user_group_add }}"
  loop_control:
    label: "{{ item.name }}"
  when: user_group_add is defined

# Loop through provided list and ensure user is not present in the system
- name: Ensure specified groups do not exist in the system
  group:
    name: "{{ item }}"
    state: absent
  loop: "{{ user_group_remove }}"
  when: user_group_remove is defined


# Loop through provided list and ensure user is in the system, with correct attributes
- name: Ensure specified user accounts exist with correct attributes
  user:
    name: "{{ item.name }}"
    comment: "{{ item.comment | default(omit, true) }}"
    uid: "{{ item.uid | default(omit, true) }}"
    group: "{{ item.group | default(omit, true) }}"
    groups: "{{ item.groups | default([], true) | join(',') | default(omit, true) }}"
    shell: "{{ item.shell }}"
    home: "{{ item.home | default(omit, true) }}"
    password: "{{ item.password | default(omit) }}"
    append: no
    update_password: always
    state: present
  loop: "{{ user_account_add }}"
  loop_control:
    label: "{{ item.name }}"
  when: user_account_add is defined

# Loop through provided list and ensure user is not present in the system
- name: Ensure specified user accounts do not exist in the system
  user:
    name: "{{ item }}"
    state: absent
    remove: yes
  loop: "{{ user_account_remove }}"
  when: user_account_remove is defined
