---
# handlers file for firewall
- name: reload firewall ipv4 service
  service:
    name: "{{ firewall_ipv4_service_name }}"
    state: reloaded
  listen: reload firewall
  when:
    - ansible_connection != "docker"

- name: reload firewall ipv6 service
  service:
    name: "{{ firewall_ipv6_service_name }}"
    state: reloaded
  listen: reload firewall
  when:
    - ansible_connection != "docker"
    - firewall_ipv6_service_name != 'unavailable'

- name: reload firewalld
  command: firewall-cmd --reload
