---
- name: Converge
  hosts: all
  tasks:

    - name: install gnupg on Debian systems
      package:
        name: gnupg
        state: present
        update_cache: yes
      when: ansible_os_family == 'Debian'

    - name: "Include podman"
      include_role:
        name: "podman"
