---

# Do not stop execution if a module do not exist but
# show an error message.
- name: Check if kernel module exists on the system.
  command: "/usr/sbin/modinfo {{ item }}"
  changed_when: false
  ignore_errors: yes
  loop: "{{ kernel_disable_modules | default([], true) }}"

# Can check only if the value was specified
- name: Check if sysctl information is valid
  assert:
    that:
      - item.name is defined and (item.name | length > 0)
      - item.value is defined and (item.value | length > 0)
    msg: "Both name and value should be defined."
  loop: "{{ kernel_sysctl | default([], true) }}"

#kernel_sysctl_flush_network_routes
- name: Check if kernel_sysctl_flush_network_routes is valid
  assert:
    that:
      - kernel_sysctl_flush_network_routes is defined
      - kernel_sysctl_flush_network_routes | type_debug == 'bool'

