---
- name: Converge
  hosts: all
  vars:
    rsyslog_log_server: loghost.example.com
    rsyslog_retry_count: -1
    rsyslog_max_disk_space: '1g'
    rsyslog_save_on_shutdown: 'on'
    rsyslog_queue_filename: 'fwdRule1'
  tasks:
    - name: "Include rsyslog"
      include_role:
        name: "rsyslog"
