---
# vars file for cron

_cron_packages:
  default:
    - cronie
  Alpine:
    - dcron
  Debian:
    - cron
  Ubuntu-20:
    - systemd-cron

cron_packages: "{{ _cron_packages[ansible_distribution ~ '-' ~ ansible_distribution_major_version] | default(_cron_packages[ansible_distribution]) | default(_cron_packages['default']) }}"

_cron_configuration:
  default: /etc/crontab
  Archlinux: /etc/conf.d/crond

cron_configuration: "{{ _cron_configuration[ansible_distribution ~ '-' ~ ansible_distribution_major_version] | default(_cron_configuration[ansible_distribution]) | default(_cron_configuration['default']) }}"

_cron_service:
  default: crond
  Alpine: '[]'
  Debian: cron
  Suse: cron
  Archlinux: cronie
  Ubuntu-20: cron.target

cron_service: "{{ _cron_service[ansible_distribution ~ '-' ~ ansible_distribution_major_version] | default(_cron_service[ansible_distribution]) | default(_cron_service['default']) }}"
