---
- name: Converge
  hosts: all
  tasks:
    - name: update packages on debian family systems
      apt:
        update_cache: yes
        cache_valid_time: 3600
      when: ansible_os_family == 'Debian'

    - name: "Include openssh_server"
      include_role:
        name: "openssh_server"
