---
# handlers file for grub

# handlers file for grub
- name: update grub
  command: "{{ grub_update_grub_command }} -o {{ grub_cfg_path }}/grub.cfg"
  when:
    - ansible_connection != "docker"
  notify:
    - reboot

- name: reboot
  reboot:
