---
- name: Converge
  hosts: all
  tasks:

    - name: Update Debian system package list
      apt:
        update_cache: yes
        cache_valid_time: 3600
      when: ansible_os_family == 'Debian'

    - name: "Include logrotate"
      include_role:
        name: "logrotate"
