---
# defaults file for sudo

# If a variable is not defined, no change will happen to 
# the setting that the variable controls. For example, 
# if sudo_log is not defined, no task will be executed
# to set sudo_log

# Any setting will be written in files on sudoers.d directory
# Choose a name to hold the settings in the scope of this role.
sudo_config_file_name: 01_ansible

# if specified, the default groups like wheel, admin, sudo will
# be disabled, and the specified group enabled, so users of the
# specified group are able to sudo to any command.
sudo_admin_group: admin

# if defined, add sudo configuration to 
# generate log at the defined location
sudo_log: /var/log/sudo.log

# A few times, attackers can run a malicious program 
# (such as a virus or malware) using sudo, which would 
# again fork a background process that remains on the user’s 
# terminal device even when the main program has finished executing.
# To avoid such a scenario, you can configure sudo to run other 
# commands only from a psuedo-pty using the use_pty parameter, 
# whether I/O logging is turned on or not, set variable below to yes.
# Setting this variable to no will only cause the role to remove 
# use_pty entry from the custom sudo file.
sudo_cmd_use_pty: yes

# This is the path used for every command run with sudo, 
# it has two importances:
#      * Used when a system administrator does not trust 
#        sudo users to have a secure PATH environment variable
#      * To separate “root path” and “user path”, only users 
#        defined by exempt_group are not affected by this setting.
#sudo_secure_path: '/sbin:/bin:/usr/sbin:/usr/bin'
