---
# vars file for crypto_policy

_cryto_policy_systems:
  RedHat: yes
  Fedora: yes
  CentOS: yes
  default: no

_enable_crypto_policy: "{{ _cryto_policy_systems[ansible_distribution ~ '-' ~ ansible_distribution_major_version] | default(_cryto_policy_systems[ansible_distribution]) | default(_cryto_policy_systems['default']) }}"

# LEGACY is not on the list because it is insecure.
_available_crypto_policies: ["DEFAULT","FUTURE","FIPS"]

