---
- name: Converge
  hosts: all
  tasks:
    - name: update cache
      apt:
        update-cache: yes
      when: ansible_os_family == 'Debian'
    - name: "Include audit"
      include_role:
        name: "audit"
