---
- name: test if firewall_selected is set correctly
  assert:
    that:
      - firewall_selected is defined
      - firewall_selected in ['ufw','iptables','firewalld']
    quiet: yes

- name: test if firewall_default_protocol is set correctly
  assert:
    that:
      - firewall_default_protocol is defined
      - firewall_default_protocol in ["tcp", "udp"]
    quiet: yes

- name: test if firewall_default_action is set correctly
  assert:
    that:
      - firewall_default_action is defined
      - firewall_default_action in ["allow", "deny"]
    quiet: yes

- name: test if firewall_services is set correctly
  assert:
    that:
      - firewall_services | length > 0
      - firewall_services is iterable
    quiet: yes
  when:
    - firewall_services is defined

- name: test if non-numeric item in firewall_services is set correctly
  assert:
    that:
      - item.name is defined
      - item.name | length > 0
    quiet: yes
  loop: "{{ firewall_services }}"
  loop_control:
    label: "{{ item.name }}"
  when:
    - firewall_services is defined
    - item.name | type_debug != "int"

- name: test if numeric item in firewall_services is set correctly
  assert:
    that:
      - item.name is defined
      - item.name | int > 0
      - item.name | int < 65536
    quiet: yes
  loop: "{{ firewall_services }}"
  loop_control:
    label: "{{ item.name }}"
  when:
    - firewall_services is defined
    - item.name | int(-1) != -1

- name: test if item with action in firewall_services is set correctly
  assert:
    that:
      - item.action in ["allow", "deny"]
    quiet: yes
  loop: "{{ firewall_services }}"
  loop_control:
    label: "{{ item.action | default('undefined') }}"
  when:
    - firewall_services is defined
    - item.action is defined

- name: test if item with zone in firewall_services is set correctly (firewalld only)
  assert:
    that:
      - item.zone | length > 0
    quiet: yes
  loop: "{{ firewall_services }}"
  loop_control:
    label: "{{ item.zone | default('undefined') }}"
  when:
    - firewall_services is defined
    - item.zone is defined
    - firewall_selected == 'firewalld'
