---

# Prevent errors, skipping tasks without having to
# add 'when: firewall_services is defined' on several
# tasks
- name: Set firewall_services as empty list if not defined
  set_fact:
    firewall_services: "{{ firewall_services | default([], true) }}"

# tasks file for firewall
- name: include assert.yml
  include_tasks: assert.yml
  run_once: yes

- name: Populate service facts
  service_facts:

- name: install required software
  package:
    name: "{{ firewall_packages_required }}"
    state: present
    update_cache: yes
  register: firewall_sw_install_result
  when:
    - firewall_packages_required is defined

- name: disable conflicting firewall services
  service:
    name: "{{ item }}"
    enabled: no
    state: stopped
  loop: "{{ firewall_packages_conflicting }}"
  when: (ansible_service_mgr == 'systemd' and ansible_facts['services'][item + '.service'] is defined) or
         ansible_facts['services'][item] is defined

- name: Ensure ipv4 service is enabled and started
  service:
    name: "{{ firewall_ipv4_service_name }}"
    state: started
    enabled: yes
  register: firewall_service_enablement_result

- name: Ensure ipv6 service is enabled and started (iptables only)
  service:
    name: "{{ firewall_ipv6_service_name }}"
    state: started
    enabled: yes
  when: firewall_ipv6_service_name != 'unavailable'


# Firewalld needs systemd to run, so skip if that is the case
- name: Run firewall software specific tasks
  include_tasks: "{{ firewall_selected }}.yml"
