---
# defaults file for audit

# maximum size of the audit log file, in MB
audit_log_file_size: 256

# If audit file already exists, force
# overwrite? It will overwrite only
# if target file contents are different 
# from source.
force_overwrite_audit: true

# If sudo role is defined, get value from there
audit_sudo_log: "{{ sudo_log | default('/var/log/sudo.log') }}"

