---
# defaults file for user settings

# If the password of the user running ansible changes
# this variable needs to have the new password, so
# ansible_become_pass and ansible_ssh_pass can be updated
#user_new_password: "{{ vault_admin_password }}"

## Password settings ##

# Number of days before password expire
user_max_days: 365

# Number of days until user is allowed to change password
user_min_days: 7

# Number of days before user is considered inactive
user_inactive_days: 30

# Number of days before password expire that will
# generate a warning to the user
user_warn_age: 7

# UMASK to be used by all users
user_umask: '027'

# Shell timeout in seconds
user_shell_timeout: 900

# Should tasks be executed to fix existing user accounts?
user_fix_existing_accounts: yes

## OPTIONAL VARIABLES ##

root_password: mypass

user_account_add:
  - name: example
    comment: This is an example
    uid: 1076
    groups: ['admin']
    shell: /bin/bash
    password: encpwd

user_account_remove:
  - removeme

user_group_add:
  - name: admin
    gid: 760

user_group_remove:
  - mygroup
