---
- name: Converge
  hosts: all
  tasks:
    - name: update cache for debian systems
      apt:
        update_cache: yes
        cache_valid_time: 3600
      when: ansible_os_family == 'Debian'

    - name: "Include selinux"
      include_role:
        name: "selinux"
