---
# handlers file for sysctl

- name: flush network routes
  sysctl:
    name: "{{ item }}"
    value: "1"
    reload: yes
    state: present
    sysctl_set: yes
  loop:
    - net.ipv4.route.flush
    - net.ipv6.route.flush
  when: kernel_sysctl_flush_network_routes

- name: reload modules
  systemd:
    name: systemd-modules-load.service
    state: restarted
  when: ansible_service_mgr == 'systemd' and
        ansible_virtualization_type not in ['docker','lxc']
