---
# handlers file for auto_update

- name: "restart dnf-automatic service"
  systemd:
    name: dnf-automatic.timer
    state: restarted

- name: "restart yum-cron service"
  systemd:
    name: dnf-automatic.timer
    state: restarted
