---
- name: Converge
  user: root
  hosts: all
  tasks:
    - name: Import test variables
      include_vars: vars/test.yml

    - name: "Include firewall"
      include_role:
        name: "firewall"
