---

- name: Validate partition input variables.
  vars:
    pathre: '^(?:[\/])$|^(?:[\/][a-zA-Z0-9_.-]+)+[\/]?$'
  assert:
    quiet: yes
    that:
      - item.name is regex(pathre)  # Check if it is a directory
      - item.autofix | lower in ['true','false']
      - (item.autofix | bool and item.unit_name is defined) or not (item.autofix | bool)  # need unit file if autofixing it
      - (item.autofix | bool and item.mount_options is defined and item.mount_options | length > 0) or not (item.autofix | bool)
    msg: "Invalid value for {{ item.name }}"
  loop: "{{ partitions }}"
  loop_control:
    label: "{{ item.name }}"

- name: Validate fs_world_writeable_fix_enabled variable
  assert:
    that:
      - fs_world_writeable_fix_enabled is defined
      - fs_world_writeable_fix_enabled | type_debug == 'bool'
    quiet: yes

- name: "Validate crypttab variables: fspart_cryptkeys_path"
  vars:
    pathre: '^(?:[\/])$|^(?:[\/][a-zA-Z0-9_.-]+)+[\/]?$'
  assert:
    that:
      - fspart_cryptkeys_path is string
      - fspart_cryptkeys_path is regex(pathre)
    quiet: yes
  when: fspart_cryptkeys_path is defined

- name: "Validate crypttab variables: fspart_crypttab_entries"
  assert:
    that:
      - fspart_crypttab_entries is sequence
    quiet: yes
  when: fspart_crypttab_entries is defined

- name: "Validate list contents of fspart_crypttab_entries"
  assert:
    that:
      - item.name is defined
      - item.name | type_debug is string
      - item.name | length > 0
      - (item.backing_device is not defined) or (item.backing_device is string)
      - (item.backing_device is not defined) or item.backing_device | length > 0
      - (item.password is not defined) or (item.password is string)
      - (item.password is not defined) or item.password | length > 0
      - (item.opts is not defined) or (item.opts is string)
      - (item.opts is not defined) or item.opts | length > 0
    quiet: yes
  when: fspart_crypttab_entries is defined
  loop: "{{ fspart_crypttab_entries | default([], true) }}"

- name: "Validate crypttab variables: fspart_cryptkeys_files"
  assert:
    that:
      - fspart_cryptkeys_files is sequence
    quiet: yes
  when: fspart_cryptkeys_files is defined

- name: "Validate list contents of fspart_cryptkeys_files"
  assert:
    that:
      - item.name is defined
      - item.name is string
      - item.name | length > 0
      - item.src is defined
      - item.src is string
      - item.src | length > 0
    quiet: yes
  when: fspart_cryptkeys_files is defined
  loop: "{{ fspart_cryptkeys_files | default([], true) }}"
