---
# tasks file for fspart

- name: Process input variables, adding default values
  import_tasks: vars_defaults.yml

- name: Check partition variables
  import_tasks: asserts.yml

- name: Check systemd unit files for each partition with autofix set to true
  include_tasks: systemdmount.yml
  loop: "{{ partitions | selectattr('autofix') | list }}"

- name: Validate mount points
  import_tasks: validate.yml

- name: Fix filesystems permissions
  import_tasks: fix_permissions.yml
