---
# defaults file for sysctl

# Use the variable below to list the kernel
# modules that should be disabled
# you might add usb-storage to the list but this will prevent any usb storage device from working. Consider using USBGuard.
#kernel_disable_modules: ['cramfs', 'freevxfs', 'jjfs2', 'hfs', 'hfsplus', 'udf', 'vfat', 'squashfs']

# Modules to be blacklisted
#kernel_blacklist_modules: ['radeon', 'amdgpu']

# Modules to be autostarted
#kernel_autostart_modules: ['br_netfilter']

#kernel_sysctl:
#  - { name: fs.suid_dumpable, value: "0" }
#  - { name: kernel.randomize_va_space, value: "2" }
#  - { name: kernel.nmi_watchdog, value: "0" }
#  - { name: vm.dirty_writeback_centisecs, value: "1500" }
#  - { name: vm.dirty_expire_centisecs, value: "3000" }
#  - { name: net.ipv4.conf.all.forwarding, value: "0" }
#  - { name: net.ipv4.conf.all.send_redirects, value: "0" }
#  - { name: net.ipv4.conf.default.send_redirects, value: "0" }
#  - { name: net.ipv6.conf.all.forwarding, value: "0" }
#  - { name: net.ipv4.conf.all.accept_source_route, value: "0" }
#  - { name: net.ipv4.conf.default.accept_source_route, value: "0" }
#  - { name: net.ipv4.conf.all.accept_redirects, value: "0" }
#  - { name: net.ipv4.conf.default.accept_redirects, value: "0" }
#  - { name: net.ipv4.conf.all.secure_redirects, value: "0" }
#  - { name: net.ipv4.conf.default.secure_redirects, value: "0" }
#  - { name: net.ipv4.conf.all.log_martians, value: "1" }
#  - { name: net.ipv4.conf.default.log_martians, value: "1" }
#  - { name: net.ipv4.icmp_echo_ignore_broadcasts, value: "1" }
#  - { name: net.ipv4.icmp_ignore_bogus_error_responses, value: "1" }
#  - { name: net.ipv4.conf.all.rp_filter, value: "1" }
#  - { name: net.ipv4.conf.default.rp_filter, value: "1" }
#  - { name: net.ipv4.tcp_syncookies, value: "1" }
#  - { name: net.ipv6.conf.all.accept_source_route, value: "0" }
#  - { name: net.ipv6.conf.default.accept_source_route, value: "0" }
#  - { name: net.ipv6.conf.all.accept_redirects, value: "0" }
#  - { name: net.ipv6.conf.default.accept_redirects, value: "0" }
#  - { name: net.ipv6.conf.all.accept_ra, value: "0" }
#  - { name: net.ipv6.conf.default.accept_ra, value: "0" }

# If set to yes, it will set net.ipv4.route.flush and
# net.ipv6.route.flush settings to 1 and reload
kernel_sysctl_flush_network_routes: yes

#### UDEV #####

# SATA Link power management policy
# Valid values are min_power, max_performance, medium_power, med_power_with_dipm
#kernel_udev_sata_link_power_mgmt: med_power_with_dipm

# Autosuspend AHCI controllers and ATA devices
#kernel_udev_autosuspend_ahci_devices: yes

# autosuspend scsi devices, driver=sd
#kernel_udev_autosuspend_scsi_devices: yes

# Disable Bluetooth
#kernel_udev_disable_bluetooth: no

# Disable wake on lan
#kernel_udev_disable_wake_on_lan: yes

# list of devices to autosuspend
# Usually linux already set autosuspend for usb hubs and other devices, so do not
# need to use this option for those. Check which devices are set to auto or not
# looking at /sys/bus/usb/devices/*/power/control
#kernel_udev_usb_autosuspend_devices:
#  - { vendor: '13fe', product: '5500' }   # Silicon power flash drive
#  - { vendor: '1532', product: '0f13', autosuspend: 120 }    # Keyboard

# list of pci devices to autosuspend
#kernel_udev_pci_autosuspend_devices:
#  - { vendor: '0x8086', device: '0x0c00' }
#  - { vendor: '0x8086', device: '0x0412' }

# Enable wlan power save?
#kernel_udev_enable_wlan_powersave: yes
