---
# tasks file for crypto_policy

- name: Check if variables are correctly set
  assert:
    that:
      - crypto_policy is defined
      - crypto_policy | length > 0
      - enable_crypto_policy is defined
      - enable_crypto_policy | type_debug == 'bool'
      - crypto_reboot_after_update is defined
      - crypto_reboot_after_update | type_debug == 'bool'
    quiet: yes


- name: Display error if crypto variable violates policy
  debug:
    msg:
      - "crypto_policy is set to: {{ crypto_policy }}. Which is not a valid selection."
      - "Valid choices are DEFAULT, FUTURE, and FIPS."
      - "LEGACY selection does not satisfy the control requirement"
      - "Refusing to update crypto_policy information"
  when:
    - (crypto_policy | upper) not in _available_crypto_policies

- name: Configure/Setup crypto-policy
  include_tasks: setup.yml
  when: enable_crypto_policy
